### ISSUE TITLE
TypeError: jhipsterFunc.addJavaScriptToIndex is not a function

### ISSUE THREAD

**Issue by Ledar** [moifort/generator-jhipster-angular-ui#12]
i try to run the module on a JHipster generated application, but it doesn't work, and i don't know what to do.

<img width="1311" alt="issue" src="https://cloud.githubusercontent.com/assets/8611541/22231616/92bb8268-e21f-11e6-8fb1-fa1a0318f528.png">

**Comment by amitjindal** [comment]
I am getting the same.

**Comment by guobingrong** [comment]
I am getting the same.

**Comment by pascalgrimaud** [comment]
This module hasn't been updated for a long time, so it doesn't work anymore
PR are welcome to update it
