### ISSUE TITLE
Failing to install w jHipster v3.3.0

### ISSUE THREAD

**Issue by gpeev** [moifort/generator-jhipster-angular-ui#9]
I've tried to install this with several different versions [v0.11.14, v0.12.7, v4.0.0, v5.0.0, v6.2.0] of node but I keep getting the same error. I can try something specific if you have a recommendation. 

I'm hoping this is an easy fix. Thanks for reviewing. 

> yo jhipster-angular-ui

``` javascript
     _-----_
    |       |    .--------------------------.
    |--(o)--|    |  Welcome to the JHipster |
   `---------´   |   AngularUI generator!   |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? Which module do you like to install on your JHipster application? Install all modules
Composing JHipster configuration with module AngularUI
Reading the JHipster project configuration for your module
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: jhipsterFunc.addJavaScriptToIndex is not a function
    at module.exports.yeoman.generators.Base.extend.writing (/usr/local/Cellar/nvm/0.20.0/versions/v4.0.0/lib/node_modules/generator-jhipster-angular-ui/generators/app/index.js:104:22)
    at /usr/local/Cellar/nvm/0.20.0/versions/v4.0.0/lib/node_modules/generator-jhipster-angular-ui/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by lrkwz** [comment]
+1

**Comment by pascalgrimaud** [comment]
Yes, it's normal.
This module need to be updated for JHipster 3.0

See https://github.com/jhipster/generator-jhipster/pull/3104 and https://github.com/jhipster/generator-jhipster/issues/3435

**Comment by pascalgrimaud** [comment]
Just updated this module.
I will PR soon -> maybe tonight or tomorrow.
Could you test and made a new release @moifort ?

**Comment by moifort** [comment]
Yes thank you a lot @pascalgrimaud, I really dont have time now, quite difficult for me. Your help is more than welcome!

**Comment by fmunozse** [comment]
Sorry for the question, but, is any date for the delivery version of this fix?

In any case, thanks in advance.

**Comment by pascalgrimaud** [comment]
@fmunozse : I've just accepted the PR here #10 
If you want to use this module, try to use directly the master. Here the step to do it:
1) git clone https://github.com/moifort/generator-jhipster-angular-ui.git
2) cd generator-jhipster-angular-ui
3) npm install
4) npm link

**Comment by fmunozse** [comment]
thanks @pascalgrimaud thats works ;)
